openapi: 3.0.1
info:
  description: Criteo API - MarketingSolutions
  title: Criteo API
  version: 2025-07
servers:
- url: https://api.criteo.com
security:
- oauth: []
tags:
- name: Advertiser
- name: Analytics
- name: Audience
- name: Campaign
- name: Creative
- name: Gateway
paths:
  /2025-07/advertisers/me:
    get:
      description: Fetch the portfolio of Advertisers for this account
      operationId: ListAdvertisers
      security:
      - oauth: []
      tags:
      - Advertiser
      x-accepts: application/json
  /2025-07/audiences/{audience-segment-id}/contactlist:
    delete:
      description: Delete all identifiers from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-accepts: application/json
    patch:
      description: Add/remove identifiers to or from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/log-level/advertisers/{advertiser-id}/report:
    post:
      description: This Statistics endpoint provides publisher data.
      operationId: GetTransparencyReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets:
    patch:
      description: Patch a list of AdSets.
      operationId: PatchAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    post:
      description: Create the specified ad set
      operationId: CreateAdSet
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}:
    get:
      description: Get the data for the specified ad set
      operationId: GetAdSet
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}/audience:
    put:
      description: Link or unlink an audience with an ad set
      operationId: UpdateAdSetAudience
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}/category-bids:
    get:
      description: Get the Category Bids for all valid Categories associated to an
        Ad Set
      operationId: GetAdSetCategoryBids
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: Patch Category Bids for one or more Categories in a single request.
        Partial success policy is followed.
      operationId: PatchAdSetCategoryBids
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}/display-multipliers:
    get:
      description: Get the Display Multipliers for all valid Categories associated
        to an Ad Set
      operationId: GetDisplayMultipliers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: Patch Display Multipliers for one or more Categories in a single
        request. Partial success policy is followed.
      operationId: PatchDisplayMultipliers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/search:
    post:
      description: Search for ad sets
      operationId: SearchAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/start:
    post:
      description: Start the specified list of ad sets
      operationId: StartAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ad-sets/stop:
    post:
      description: Stop the specified list of ad sets
      operationId: StopAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/ads/{id}:
    delete:
      description: Delete an Ad
      operationId: DeleteAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Get an Ad with its id
      operationId: GetAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/ads:
    get:
      description: Get the list of self-services Ads for a given advertiser
      operationId: GetAdvertiserAds
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
    post:
      description: Create an Ad
      operationId: CreateAdvertiserAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons:
    get:
      description: Get the list of self-services Coupons for a given advertiser
      operationId: GetAdvertiserCoupons
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
    post:
      description: Create a Coupon
      operationId: CreateAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons-supported-sizes:
    get:
      description: Get the list of Coupon supported sizes
      operationId: GetAdvertiserCouponSupportedSizes
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}:
    delete:
      description: Delete a Coupon
      operationId: DeleteAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Get a Coupon with its id
      operationId: GetAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
    put:
      description: Edit a specific Coupon
      operationId: EditAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}/preview:
    get:
      description: Get the preview of a specific Coupon
      operationId: GetAdvertiserCouponPreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/creatives:
    get:
      description: Get the list of self-services Creatives for a given advertiser
      operationId: GetAdvertiserCreatives
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
    post:
      description: Create a Creative
      operationId: CreateAdvertiserCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments:
    patch:
      description: "Updates the properties of all segments with a valid configuration,\
        \ and returns their IDs. For those that cannot be updated, one or multiple\
        \ errors are returned."
      operationId: UpdateAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/{audience-segment-id}/contact-list:
    delete:
      description: Delete all identifiers from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-accepts: application/json
    patch:
      description: Add/remove identifiers to or from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/{audience-segment-id}/contact-list/statistics:
    get:
      description: Returns the statistics of a contact list segment.
      operationId: GetAudienceSegmentContactListStatistics
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      tags:
      - Audience
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/compute-sizes:
    post:
      description: Gets the size of all segments. An error is returned for those whose
        size calculation is not supported.
      operationId: ComputeAudienceSegmentsSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/create:
    post:
      description: "Creates all segments with a valid configuration, and returns their\
        \ IDs. For those that cannot be created, one or multiple errors are returned."
      operationId: CreateAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/delete:
    post:
      description: Delete the segments associated to the given audience IDs.
      operationId: DeleteAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/estimate-size:
    post:
      description: Gets the size estimation of a non existent segment. An error is
        returned when size calculation is not supported.
      operationId: EstimateAudienceSegmentsSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/in-market-brands:
    get:
      description: Returns a list with all available in-market brands that can be
        used to define an in-market segment.
      operationId: GetAudienceSegmentsInMarketBrands
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      tags:
      - Audience
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/in-market-interests:
    get:
      description: Returns a list with all available in-market interests that can
        be used to define an in-market segment. These in-market interests correspond
        to the Google product taxonomy.
      operationId: GetAudienceSegmentsInMarketInterests
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      tags:
      - Audience
      x-accepts: application/json
  /2025-07/marketing-solutions/audience-segments/search:
    post:
      description: "Returns a list of segments that match the provided filters. If\
        \ present, the filters are AND'ed together when applied."
      operationId: SearchAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audiences:
    patch:
      description: "Updates the properties of all audiences with a valid configuration,\
        \ and returns their IDs. For those that cannot be updated, one or multiple\
        \ errors are returned."
      operationId: UpdateAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audiences/compute-sizes:
    post:
      description: Gets the size of all audiences. An error is returned for those
        whose size calculation is not supported.
      operationId: ComputeAudiencesSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audiences/create:
    post:
      description: "Creates all audiences with a valid configuration, and returns\
        \ their IDs. For those that cannot be created, one or multiple errors are\
        \ returned."
      operationId: CreateAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audiences/delete:
    post:
      description: Deletes the audiences associated to the given audience IDs.
      operationId: DeleteAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audiences/estimate-size:
    post:
      description: Gets the size estimation of a non existent audience. An error is
        returned when size calculation is not supported.
      operationId: EstimateAudiencesSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/audiences/search:
    post:
      description: "Returns a list of audiences that match the provided filters. If\
        \ present, the filters are AND'ed together when applied."
      operationId: SearchAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      tags:
      - Audience
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/campaigns:
    patch:
      description: Patch a list of Campaigns.
      operationId: PatchCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    post:
      description: Create the specified campaign
      operationId: CreateCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/campaigns/{campaign-id}:
    get:
      description: Get the data for the specified campaign
      operationId: GetCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/campaigns/search:
    post:
      description: Search for campaigns
      operationId: SearchCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/creatives/{id}:
    delete:
      description: Delete a Creative if there are no ads binded to it
      operationId: DeleteCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-accepts: application/json
    get:
      description: Get a Creative with its id
      operationId: GetCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      tags:
      - Creative
      x-accepts: application/json
    put:
      description: Edit a specific Creative
      operationId: EditCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/creatives/{id}/preview:
    post:
      description: Get the preview of a specific Creative
      operationId: GenerateCreativePreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      tags:
      - Creative
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers:
    get:
      description: Get the collection of advertisers associated with the user.
      operationId: GetMarketplaceAdvertisers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}:
    get:
      description: Get an advertiser.
      operationId: GetMarketplaceAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/ad-preview:
    get:
      description: "Get a preview of an HTML ad with products belonging to the provided\
        \ seller\r\n• <b>advertiserId</b>: Valid crp advertiserId, seller belongs\
        \ to provided advertiser<br />\r\n• <b>sellerId</b>: Products from given SellerId\
        \ will fill the ad preview, must be existing crp sellerId<br />\r\n• <b>height</b>:\
        \ height may be supplied to request a specific ad preview height. Default\
        \ height: 250<br />\r\n• <b>width</b>: width may be supplied to request a\
        \ specific ad preview width. Default width: 300<br />\r\n            \r\n\
        Ad preview api calls are capped to 1000 per day per advertiser by default.\
        \ Current usage, limit, and period can be found using v2/crp/advertisers/preview-limit"
      operationId: GetMarketplaceSellerAdPreview
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/adsets:
    get:
      description: Get the collection of adsets associated with the advertiserId.
      operationId: GetMarketplaceAdSetsByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/budgets:
    get:
      description: Get CRP budgets for a specific advertiser
      operationId: GetMarketplaceBudgetsByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/campaigns:
    get:
      description: Get the collection of CRP campaigns associated with the advertiserId.
      operationId: GetMarketplaceCampaignsByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/seller-campaigns:
    get:
      description: Get CRP seller campaigns for a specific advertiser
      operationId: GetMarketplaceSellerCampaignsByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/sellers:
    post:
      description: Create new sellers for an advertiser
      operationId: GetMarketplaceSellersByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/preview-limit:
    get:
      description: Get the collection of advertisers preview limits associated with
        the authorized user.
      operationId: GetMarketplaceAdvertiserPreviewLimits
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/budgets:
    get:
      description: "Return a collection of budgets filtered by optional filter parameters.\r\
        \nIf all parameters are omitted the entire collection to which the user has\r\
        \naccess is returned, except those whose endDate is in the past. Returned\
        \ budgets must satisfy all supplied filter\r\ncriteria if multiple parameters\
        \ are used.\r\n            \r\n<b>Date filter.</b> Filtering can return only\
        \ budgets that were active for a\r\ndate range by specifying the startBeforeDate\
        \ and endAfterDate. Leaving off the startBeforeDate\r\nvalue makes budgets\
        \ with any startDate qualify, whereas when leaving off the endAfterDate value\
        \ will only return\r\nbudgets whose endDate has not already passed. To get\
        \ budgets that were active\r\non a specific date, set both values to that\
        \ day.\r\n            \r\n<b>Spend.</b> If the endAfterDate is supplied, the\
        \ spend excludes spend that\r\nhappened after that date. In the case of a\
        \ daily budget, only the spend for\r\nthe final day is displayed.\r\n    \
        \        \r\nSee the budgets endpoint for additional details."
      operationId: GetMarketplaceSellerBudgets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: "Modify one or more existing active budgets to change their limitations\
        \ or status.\r\nAll three types of budgets can be modified.\r\n          \
        \  \r\nThe following constraints apply when modifying an existing budget.\r\
        \n            \r\n• <b>campaignIds</b>: a non-empty subset of the original\
        \ campaign ids MAY be supplied<br />\r\n• <b>amount</b>: an amount MAY be\
        \ supplied only if the type is not Uncapped and if supplied it MUST be non-negative<br\
        \ />\r\n• <b>startDate</b>: a future start date MAY be supplied for budgets\
        \ that have not yet started<br />\r\n• <b>endDate</b>: an end date MAY be\
        \ supplied and if supplied MUST be a future date greater than the start date<br\
        \ />\r\n            \r\nOther attributes MUST NOT be supplied.\r\n       \
        \     \r\nAdding new campaigns to a budget is not allowed. In addition, reducing\
        \ the amount for\r\na Capped budget to a value less than the current spend\
        \ not allowed."
      operationId: UpdateMarketplaceSellerBudgets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
    post:
      description: "Create one or more new budgets to enable spending with the given\
        \ limitations.\r\nAll three types of budgets can be created this way.\r\n\
        \            \r\nThe following constraints apply when creating a new budget.\r\
        \n            \r\n• <b>sellerId</b>: the seller MUST be supplied<br />\r\n\
        • <b>campaignIds</b>: a non-empty array of campaign ids MUST be supplied<br\
        \ />\r\n• <b>budgetType</b>: a budget type MUST be supplied<br />\r\n• <b>amount</b>:\
        \ an amount MAY be supplied only if the type is not Uncapped and if supplied\
        \ it MUST be non-negative<br />\r\n• <b>startDate</b>: a future start date\
        \ MUST be supplied<br />\r\n• <b>endDate</b>: an end date MAY be supplied\
        \ and if supplied MUST be greater than the start date<br />\r\n          \
        \  \r\nOther attributes MUST NOT be supplied."
      operationId: CreateMarketplaceSellerBudgets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/budgets/{budgetId}:
    get:
      description: "Return a budget. For example,\r\n            \r\n    {\r\n   \
        \     \"id\": \"1759183\",\r\n        \"sellerId\": \"321392\",\r\n      \
        \  \"campaignIds\": [\r\n            143962\r\n        ],\r\n        \"budgetType\"\
        : \"Capped\",\r\n        \"amount\": 1000,\r\n        \"startDate\": \"2021-01-11\"\
        ,\r\n        \"endDate\": \"2021-01-12\",\r\n        \"spend\": null,\r\n\
        \        \"status\": \"Active\"\r\n    }\r\n            \r\nA budget limits\
        \ the spend of a seller for one or more campaigns.\r\n            \r\nThere\
        \ are three types of budget:<br /><b>Uncapped</b> budgets put no limit on\
        \ the total amount of spend.<br /><b>Capped</b> budgets limit the total spend\
        \ to a fixed amount.<br /><b>Daily</b> budgets limit daily spend to a fixed\
        \ amount.<br />\r\n            \r\nIn addition, budgets can limit the spend\
        \ to a specific range of dates using\r\nthe start and end date attributes.\
        \ Finally a budget must be active to be used.\r\n            \r\n<b>Spend</b>\
        \ approximates the current spend against this budget. There may be a lag\r\
        \nbetween when an ad is clicked and the time it accrues to the spend. Daily\
        \ budgets\r\nshow spend against the most recent day only."
      operationId: GetMarketplaceSellerBudget
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: "Modify an existing active budget to change its limitations or\
        \ status.\r\nAll three types of budgets can be modified.\r\n            \r\
        \nSee the additional restrictions listed in the PATCH budgets endpoint."
      operationId: UpdateMarketplaceSellerBudget
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/seller-campaigns:
    get:
      description: "Return a collection of seller campaigns filtered by optional filter\
        \ parameters.\r\nIf all parameters are omitted the entire collection to which\
        \ the user has\r\naccess is returned. Returned sellers must satisfy all supplied\
        \ filter\r\ncriteria if multiple parameters are used."
      operationId: GetMarketplaceSellerCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: "Patching a collection of seller campaigns allows their bids to\
        \ be modified.\r\nEach bid must be a non-negative value. Setting the bid to\
        \ zero will make a seller campaign inactive.\r\n            \r\nThe currency\
        \ used for bids will be the default currency of the campaign."
      operationId: UpdateMarketplaceSellerCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/seller-campaigns/{sellerCampaignId}:
    get:
      description: "Return details for a seller campaign. For example,\r\n       \
        \     \r\n    {\r\n        \"id\": \"543210.123456\",\r\n        \"sellerId\"\
        : \"543210\",\r\n        \"campaignId\": 123456,\r\n        \"bid\": 1.55,\r\
        \n        \"suspendedSince\": \"2018-07-30T15:15:24.813\",\r\n        \"suspensionReasons\"\
        : [\r\n            \"NoMoreBudget\"\r\n        ]\r\n    }\r\n            \r\
        \nAn active seller campaign is one for which the value of <b>suspendedSince</b>\
        \ is null and\r\nthe <b>bid</b> is positive. The currency of the bid is the\
        \ <b>bidCurrency</b> of the\r\nassociated campaign.\r\n            \r\nAny\
        \ active seller campaign must also have an active total (capped or uncapped)\
        \ budget.\r\nIt may optionally have an active daily budget as well to further\
        \ limit spending.\r\n            \r\nSuspension reasons:\r\n- ManuallyStopped:\
        \ The Seller-Campaign has been manually paused. This is not related to the\
        \ other suspension reasons.\r\n- NoBudgetDefined: No valid budget has been\
        \ linked to the Seller-Campaign.\r\n- NoCpcDefined: No CPC has been set for\
        \ the Seller-Campaign.\r\n- NoMoreBudget: The current budget of the Seller-Campaign\
        \ has been exhausted.\r\n- RemovedFromCatalog: All the products of the Seller-Campaign\
        \ have been deleted from the catalog.\r\n- NotYetStarted: The Seller-Campaign\
        \ has just been created and has not yet been processed."
      operationId: GetMarketplaceSellerCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
    patch:
      description: "Patching a seller campaign allows the bid to be modified. The\
        \ bid must be a non-negative value.\r\nSetting the bid to zero will make a\
        \ seller campaign inactive.\r\n            \r\nThe currency used for bids\
        \ will be the default currency of the campaign."
      operationId: UpdateMarketplaceSellerCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/seller-campaigns/{sellerCampaignId}/budgets:
    get:
      description: "Return a collection of budgets for this seller campaign filtered\
        \ by optional filter parameters.\r\nIf all parameters are omitted the entire\
        \ collection to which the user has\r\naccess is returned, except those whose\
        \ endDate is in the past. Returned budgets must satisfy all supplied filter\r\
        \ncriteria if multiple parameters are used.\r\n            \r\nSee the budgets\
        \ endpoint for additional details."
      operationId: GetMarketplaceBudgetsBySellerCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers:
    get:
      description: "Return a collection of sellers filtered by optional filter parameters.\r\
        \nIf all parameters are omitted the entire collection to which the user has\r\
        \naccess is returned. Returned sellers must satisfy all supplied filter\r\n\
        criteria if multiple parameters are used."
      operationId: GetMarketplaceSellers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers/{sellerId}:
    get:
      description: "Return details for the selected seller. For example,\r\n     \
        \       \r\n    {\r\n        \"id\" : \"123456\"\r\n        \"sellerName\"\
        : \"HBogart\",\r\n    }"
      operationId: GetMarketplaceSeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers/{sellerId}/budgets:
    get:
      description: "Return a collection of budgets for this seller filtered by optional\
        \ filter parameters.\r\nIf all parameters are omitted the entire collection\
        \ to which the user has\r\naccess is returned, except those whose endDate\
        \ is in the past. Returned budgets must satisfy all supplied filter\r\ncriteria\
        \ if multiple parameters are used. See the budgets endpoint for additional\
        \ details."
      operationId: GetMarketplaceBudgetsBySeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers/{sellerId}/seller-campaigns:
    get:
      description: "Return a collection of seller campaigns for this seller filtered\
        \ by optional filter parameters.\r\nIf all parameters are omitted the entire\
        \ collection to which the user has\r\naccess is returned. Returned sellers\
        \ must satisfy all supplied filter\r\ncriteria if multiple parameters are\
        \ used. See the seller campaigns endpoint for additional details."
      operationId: GetMarketplaceSellerCampaignsBySeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
    post:
      description: Associate an existing Seller with an existing Campaign allowing
        for budget creation
      operationId: CreateMarketplaceSellerCampaignsBySeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: ""
      tags:
      - Campaign
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/stats/campaigns:
    get:
      description: "## Dimensions\r\n            \r\nGet performance statistics aggregated\
        \ for _campaigns_. The campaign id appears\r\nin the output as the first column.\r\
        \n            \r\nAggregation can be done by `hour`, `day`, `month`, or `year`\
        \ aligned with the user timezone\r\nif provided. The aggregation interval\
        \ size is controlled by `intervalSize`. The time\r\ninterval appears in the\
        \ output as the second column.\r\n            \r\n## Metrics\r\n         \
        \   \r\nThe metrics reported by this endpoint are\r\n            \r\n.  |\
        \ Metric Group | Description\r\n---|--------------|------------\r\nA | impressions\
        \ | Number of times product is shown in a banner\r\nB | clicks | Number of\
        \ clicks on product\r\nC | cost | Amount spent for clicks on products\r\n\
        D | saleUnits | Number of products sold attributed to clicks\r\nE | revenue\
        \ | Revenue generated by sales\r\nF | CR = Conversion Rate | salesUnits /\
        \ clicks\r\nG | CPO = Cost Per Order | cost / salesUnits\r\nH | COS = Cost\
        \ of Sale | cost / revenue\r\nI | ROAS = Return On Add Spend | revenue / cost\r\
        \n            \r\nThe last six metrics can be computed in two ways depending\
        \ on the policy to count only\r\nthe sales that result from clicks on the\
        \ same sellers product in a banner\r\n(same-seller) or not (any-seller). \
        \ Reporting can be controlled by `clickAttributionPolicy`.\r\n           \
        \ \r\nThe 9 (or 15) metric values appear in the output as the final 9 (or\
        \ 15) columns.\r\n            \r\n## Filtering\r\n            \r\nThe results\
        \ can be filtered by campaign, date or count.\r\n            \r\nFiltering\
        \ the results to events associated with a specific campaign is done by setting\r\
        \nthe `campaignId` filter parameter to the desired value.\r\n            \r\
        \nFiltering the results to events\r\nthat happened in a time interval is done\
        \ by setting the `startDate` and\r\n`endDate` filter parameters using the\
        \ `yyyy-MM-DD` format. The start date\r\nincludes all events timestamped since\
        \ the beginning of that day while the end\r\ndate includes events until the\
        \ end of day. The maximum duration of the date\r\nrange is 1 year. If the\
        \ aggregation interval is `hour`, then the maximum\r\nduration of the date\
        \ range is 31 days. Note that month and year aggregate values\r\nmay contain\
        \ partial data for the interval if filtering by date.\r\n            \r\n\
        Filtering the results to a maximum number of data rows is done by setting\
        \ the\r\n`count` filter parameter. When combined with startDate this can be\
        \ used to perform\r\nsimple pagination.\r\n            \r\n## Response Format\r\
        \n            \r\nThe representation format can be specified by MIME values\
        \ in the Accept header.\r\nFor now the only supported values for the accept\
        \ header is `application/json` and\r\n`text/csv`.\r\n            \r\n```json\r\
        \n{\r\n   \"columns\": [ \"campaignId\", \"month\", \"impressions\", \"clicks\"\
        , \"cost\", \"saleUnits\", \"revenue\", \"cr\", \"cpo\", \"cos\", \"roas\"\
        \ ],\r\n   \"data\": [\r\n       [168423, \"2019-05-01\", 3969032, 13410,\
        \ 1111.295, 985, 190758099, 0.073, 1.128, 0.000, 171653.880 ],\r\n       [168423,\
        \ \"2019-06-01\", 8479603, 25619, 2190.705, 740, 152783656, 0.028, 2.960,\
        \ 0.000, 69741.775 ]\r\n       ],\r\n   \"rows\": 2\r\n}\r\n```\r\n      \
        \      \r\nThe JSON result is an object with three fields (`columns`, `data`,\
        \ and `rows`). The\r\n“columns” array acts as the header for the data rows.\
        \ The categorical dimension\r\ncolumn comes first and consists of the campaign\
        \ id.\r\nThe interval column comes next and defines the aggregation period.\
        \  The interval size is\r\ndetermined by the `intervalSize` parameter. This\
        \ is followed by either nine or\r\nfifteen metrics columns. The first three\
        \ metrics (impressions, clicks, and cost)\r\nalways appear. The remaining\
        \ depend on the `clickAttributionPolicy` parameter.\r\n            \r\nThe\
        \ “data” array contains data rows whose values match the entries in the\r\n\
        “columns” array. Id dimensions are numbers while name and date dimensions\
        \ are strings. The metrics are JSON objects\r\nwhose type is number. Some\
        \ of these are natural numbers (e.g. clicks and\r\nimpressions) whereas others\
        \ are decimal values. A divide by zero yields null. The\r\ncurrency is assumed\
        \ to be the local currency established by the advertiser.\r\n            \r\
        \nThe “row” value is a count of the number of rows in the data array, and\
        \ can be\r\nused to check the integrity of the data.\r\n            \r\nFurther\
        \ information on the campaign or seller (e.g. the seller name) can be\r\n\
        obtained from the existing V1 or V2 endpoints using the campaign and/or seller\r\
        \nID values."
      operationId: GetMarketplaceCampaignsStats
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/stats/seller-campaigns:
    get:
      description: "## Dimensions\r\n            \r\nGet performance statistics aggregated\
        \ for _seller campaigns_.The campaign id, seller id, and\r\nseller name appear\
        \ in the first three columns of the output. These are followed by the interval\r\
        \nsize column.\r\n            \r\nAggregation can be done by `hour`, `day`,\
        \ `month`, or `year` aligned with the user timezone if\r\nprovided. The aggregation\
        \ interval size is controlled by `intervalSize`. The remaining columns\r\n\
        are metrics.\r\n            \r\n## Metrics\r\n            \r\nThe metrics\
        \ reported by this endpoint are\r\n            \r\n.  | Metric Group | Description\r\
        \n---|--------------|------------\r\nA | impressions | Number of times product\
        \ is shown in a banner\r\nB | clicks | Number of clicks on product\r\nC |\
        \ cost | Amount spent for clicks on products\r\nD | saleUnits | Number of\
        \ products sold attributed to clicks\r\nE | revenue | Revenue generated by\
        \ sales\r\nF | CR = Conversion Rate | salesUnits / clicks\r\nG | CPO = Cost\
        \ Per Order | cost / salesUnits\r\nH | COS = Cost of Sale | cost / revenue\r\
        \nI | ROAS = Return On Add Spend | revenue / cost\r\n            \r\nThe last\
        \ six metrics can be computed in two ways depending on the policy to count\
        \ only\r\nthe sales that result from clicks on the same sellers product in\
        \ a banner\r\n(same-seller) or not (any-seller).  Reporting can be controlled\
        \ by `clickAttributionPolicy`.\r\n            \r\nThe 9 (or 15) metric values\
        \ appear in the output as the final 9 (or 15) columns.\r\n            \r\n\
        ## Filtering\r\n            \r\nThe results can be filtered by date or count.\r\
        \n            \r\nFiltering the results to events associated with a specific\
        \ campaign is done by setting\r\nthe `campaignId` filter parameter to the\
        \ desired value.\r\n            \r\nFiltering the results to events associated\
        \ with a specific seller is done by setting\r\nthe `sellerId` filter parameter\
        \ to the desired value.\r\n            \r\nFiltering the results to events\r\
        \nthat happened in a time interval is done by setting the `startDate` and\r\
        \n`endDate` filter parameters using the `yyyy-MM-DD` format. The start date\r\
        \nincludes all events timestamped since the beginning of that day while the\
        \ end\r\ndate includes events until the end of day. The maximum duration of\
        \ the date\r\nrange is 1 year. If the aggregation interval is `hour`, then\
        \ the maximum\r\nduration of the date range is 31 days. Note that month and\
        \ year aggregate values\r\nmay contain partial data for the interval if filtering\
        \ by date.\r\n            \r\nFiltering the results to a maximum number of\
        \ data rows is done by setting the\r\n`count` filter parameter. When combined\
        \ with startDate this can be used to perform\r\nsimple pagination.\r\n   \
        \         \r\n## Response Format\r\n            \r\nThe representation format\
        \ can be specified by MIME values in the Accept header.\r\nFor now the only\
        \ supported values for the accept header is `application/json` and\r\n`text/csv`.\r\
        \n            \r\n```json\r\n{\r\n    \"columns\": [\r\n        \"campaignId\"\
        , \"sellerId\", \"sellerName\", \"month\", \"impressions\", \"clicks\", \"\
        cost\", \"saleUnits\", \"revenue\", \"cr\", \"cpo\", \"cos\", \"roas\"\r\n\
        \    ],\r\n    \"data\": [\r\n        [168423, 1110222, \"118883955\", \"\
        2019-05-01\", 14542, 48, 3.36, 0, 0.0, 0.0, null, null, 0.0],\r\n        [168423,\
        \ 1110222, \"118883955\", \"2019-06-01\", 16619, 53, 3.71, 0, 0.0, 0.0, null,\
        \ null, 0.0],\r\n        [168423, 1110225, \"117980027\", \"2019-05-01\",\
        \ 12502, 48, 3.36, 0, 0.0, 0.0, null, null, 0.0],\r\n        [168423, 1110225,\
        \ \"117980027\", \"2019-06-01\", 20266, 53, 3.71, 0, 0.0, 0.0, null, null,\
        \ 0.0]\r\n    ],\r\n    \"rows\": 4\r\n}\r\n```\r\n            \r\nThe JSON\
        \ result is an object with three fields (`columns`, `data`, and `rows`). The\r\
        \n“columns” array acts as the header for the data rows. The categorical dimension\r\
        \ncolumns come first and include the campaign id, seller id, and seller name.\r\
        \nThe interval column comes next and defines the aggregation period. The interval\
        \ size is\r\ndetermined by the `intervalSize` parameter. This is followed\
        \ by either nine or\r\nfifteen metrics columns. The first three metrics (impressions,\
        \ clicks, and cost)\r\nalways appear. The remaining depend on the `clickAttributionPolicy`\
        \ parameter.\r\n            \r\nThe “data” array contains data rows whose\
        \ values match the entries in the\r\n“columns” array. Id dimensions are numbers\
        \ while name and date dimensions are strings. The metrics are JSON objects\r\
        \nwhose type is number. Some of these are natural numbers (e.g. clicks and\r\
        \nimpressions) whereas others are decimal values. A divide by zero yields\
        \ null. The\r\ncurrency is assumed to be the local currency established by\
        \ the advertiser.\r\n            \r\nThe “row” value is a count of the number\
        \ of rows in the data array, and can be\r\nused to check the integrity of\
        \ the data.\r\n            \r\nFurther information on the campaign or seller\
        \ (e.g. the seller name) can be\r\nobtained from the existing V1 or V2 endpoints\
        \ using the campaign and/or seller\r\nID values."
      operationId: GetMarketplaceSellerCampaignsStats
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/marketplace-performance-outcomes/stats/sellers:
    get:
      description: "## Dimensions\r\n            \r\nGet performance statistics aggregated\
        \ for _sellers_. The seller id appears\r\nin the output in the first column\
        \ and the seller name appears in the second.\r\n            \r\nAggregation\
        \ can be done by `hour`, `day`, `month`, or `year` aligned with the user timezone\r\
        \nif provided. The aggregation interval size is controlled by `intervalSize`.\
        \ The time interval\r\nappears in the output as the second column.\r\n   \
        \         \r\n## Metrics\r\n            \r\nThe metrics reported by this endpoint\
        \ are\r\n            \r\n.  | Metric Group | Description\r\n---|--------------|------------\r\
        \nA | impressions | Number of times product is shown in a banner\r\nB | clicks\
        \ | Number of clicks on product\r\nC | cost | Amount spent for clicks on products\r\
        \nD | saleUnits | Number of products sold attributed to clicks\r\nE | revenue\
        \ | Revenue generated by sales\r\nF | CR = Conversion Rate | salesUnits /\
        \ clicks\r\nG | CPO = Cost Per Order | cost / salesUnits\r\nH | COS = Cost\
        \ of Sale | cost / revenue\r\nI | ROAS = Return On Add Spend | revenue / cost\r\
        \n            \r\nThe last six metrics can be computed in two ways depending\
        \ on the policy to count only\r\nthe sales that result from clicks on the\
        \ same sellers product in a banner\r\n(same-seller) or not (any-seller). \
        \ Reporting can be controlled by `clickAttributionPolicy`.\r\n           \
        \ \r\nThe 9 (or 15) metric values appear in the output as the final 9 (or\
        \ 15) columns.\r\n            \r\n## Filtering\r\n            \r\nThe results\
        \ can be filtered by seller id, date or count.\r\n            \r\nFiltering\
        \ the results to events associated with a specific seller is done by setting\r\
        \nthe `sellerId` filter parameter to the desired value.\r\n            \r\n\
        Filtering the results to events\r\nthat happened in a time interval is done\
        \ by setting the `startDate` and\r\n`endDate` filter parameters using the\
        \ `yyyy-MM-DD` format. The start date\r\nincludes all events timestamped since\
        \ the beginning of that day while the end\r\ndate includes events until the\
        \ end of day. The maximum duration of the date\r\nrange is 1 year. If the\
        \ aggregation interval is `hour`, then the maximum\r\nduration of the date\
        \ range is 31 days. Note that month and year aggregate values\r\nmay contain\
        \ partial data for the interval if filtering by date.\r\n            \r\n\
        Filtering the results to a maximum number of data rows is done by setting\
        \ the\r\n`count` filter parameter. When combined with startDate this can be\
        \ used to perform\r\nsimple pagination.\r\n            \r\n## Response Format\r\
        \n            \r\nThe representation format can be specified by MIME values\
        \ in the Accept header.\r\nFor now the only supported values for the accept\
        \ header is `application/json` and\r\n`text/csv`.\r\n            \r\n```json\r\
        \n{\r\n    \"columns\": [\"sellerId\", \"sellerName\", \"month\", \"impressions\"\
        , \"clicks\", \"cost\", \"saleUnits\", \"revenue\", \"cr\", \"cpo\", \"cos\"\
        , \"roas\"],\r\n    \"data\": [\r\n       [1200972, \"sellerA\", \"2019-05-01\"\
        , 14542, 48, 3.36, 0, 0.0, 0.0, null, null, 0.0],\r\n       [1200972, \"sellerA\"\
        , \"2019-06-01\", 16619, 53, 3.71, 0, 0.0, 0.0, null, null, 0.0],\r\n    \
        \   [1200974, \"sellerB\", \"2019-05-01\", 10102, 47, 3.29, 3, 396000.0, 0.063,\
        \ 1.096, 8.308E-6, 120364.741],\r\n       [1200974, \"sellerB\", \"2019-06-01\"\
        , 11576, 54, 3.78, 1, 132000.0, 0.018, 3.78, 2.863E-5, 34920.634]\r\n    ],\r\
        \n    \"rows\": 4\r\n}\r\n```\r\n            \r\nThe JSON result is an object\
        \ with three fields (`columns`, `data`, and `rows`). The\r\n“columns” array\
        \ acts as the header for the data rows. The categorical dimension\r\ncolumns\
        \ come first and include the seller id and seller name.\r\nThe interval column\
        \ comes next and defines the aggregation period. The interval size is\r\n\
        determined by the `intervalSize` parameter. This is followed by either nine\
        \ or\r\nfifteen metrics columns. The first three metrics (impressions, clicks,\
        \ and cost)\r\nalways appear. The remaining metrics depend on the `clickAttributionPolicy`\
        \ parameter.\r\n            \r\nThe “data” array contains data rows whose\
        \ values match the entries in the\r\n“columns” array. Id dimensions are numbers\
        \ while name and date dimensions are strings. The metrics are JSON objects\r\
        \nwhose type is number. Some of these are natural numbers (e.g. clicks and\r\
        \nimpressions) whereas others are decimal values. A divide by zero yields\
        \ null. The\r\ncurrency is assumed to be the local currency established by\
        \ the advertiser.\r\n            \r\nThe “row” value is a count of the number\
        \ of rows in the data array, and can be\r\nused to check the integrity of\
        \ the data.\r\n            \r\nFurther information on the campaign or seller\
        \ (e.g. the seller name) can be\r\nobtained from the existing V1 or V2 endpoints\
        \ using the campaign and/or seller\r\nID values."
      operationId: GetMarketplaceSellersStats
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: ""
      tags:
      - Campaign
      x-accepts: application/json
  /2025-07/marketing-solutions/me:
    get:
      description: Get information about the currently logged application
      operationId: GetCurrentApplication
      security:
      - oauth: []
      tags:
      - Gateway
      x-accepts: application/json
  /2025-07/placements/report:
    post:
      description: "Your ads are placed in different domains (publishers) and environments\
        \ (websites and apps). Thanks to the placements endpoint, you can analyse\
        \ the performances for each publisher, comparing displays, clicks and sales\
        \ generated."
      operationId: GetPlacementsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/statistics/report:
    post:
      description: "This Statistics endpoint provides adset related data. It is an\
        \ upgrade of our previous Statistics endpoint, and includes new metrics and\
        \ customization capabilities."
      operationId: GetAdsetReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
  /2025-07/transactions/report:
    post:
      description: This Transactions endpoint provides transactions id related data.
      operationId: GetTransactionsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      tags:
      - Analytics
      x-content-type: application/json
      x-accepts: application/json
components:
  securitySchemes:
    oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          scopes: {}
          tokenUrl: https://api.criteo.com/oauth2/token
        clientCredentials:
          scopes: {}
          tokenUrl: https://api.criteo.com/oauth2/token
      type: oauth2
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby

