/*
 * Criteo API
 * Criteo publicly exposed API
 *
 * The version of the OpenAPI document: preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.marketingsolutions.preview.model.CriteoApiErrorV2;
import com.criteo.api.marketingsolutions.preview.model.CriteoApiWarningV2;
import com.criteo.api.marketingsolutions.preview.model.EntityV2OfObject;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Advertiser Creation Response
 */
@ApiModel(description = "Advertiser Creation Response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AdvertiserCreationResponse {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private EntityV2OfObject data;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<CriteoApiErrorV2> errors = null;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private List<CriteoApiWarningV2> warnings = null;


  public AdvertiserCreationResponse data(EntityV2OfObject data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EntityV2OfObject getData() {
    return data;
  }


  public void setData(EntityV2OfObject data) {
    this.data = data;
  }


  public AdvertiserCreationResponse errors(List<CriteoApiErrorV2> errors) {
    
    this.errors = errors;
    return this;
  }

  public AdvertiserCreationResponse addErrorsItem(CriteoApiErrorV2 errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Error list returned by the Criteo API  For successful requests it is empty
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error list returned by the Criteo API  For successful requests it is empty")

  public List<CriteoApiErrorV2> getErrors() {
    return errors;
  }


  public void setErrors(List<CriteoApiErrorV2> errors) {
    this.errors = errors;
  }


  public AdvertiserCreationResponse warnings(List<CriteoApiWarningV2> warnings) {
    
    this.warnings = warnings;
    return this;
  }

  public AdvertiserCreationResponse addWarningsItem(CriteoApiWarningV2 warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Warnings list returned by the Criteo API  In some situations the operations are successful but it may be useful to issue warnings to the API consumer.  For example the endpoint, entity or field is deprecated. Warnings are like compiler warnings, they indicate that problems may occur in the future.
   * @return warnings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Warnings list returned by the Criteo API  In some situations the operations are successful but it may be useful to issue warnings to the API consumer.  For example the endpoint, entity or field is deprecated. Warnings are like compiler warnings, they indicate that problems may occur in the future.")

  public List<CriteoApiWarningV2> getWarnings() {
    return warnings;
  }


  public void setWarnings(List<CriteoApiWarningV2> warnings) {
    this.warnings = warnings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvertiserCreationResponse advertiserCreationResponse = (AdvertiserCreationResponse) o;
    return Objects.equals(this.data, advertiserCreationResponse.data) &&
        Objects.equals(this.errors, advertiserCreationResponse.errors) &&
        Objects.equals(this.warnings, advertiserCreationResponse.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errors, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvertiserCreationResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

