/*
 * Criteo API
 * Criteo publicly exposed API
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Metadata for the audience search response.
 */
@ApiModel(description = "Metadata for the audience search response.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AudienceSearchMetadataV1 {
  public static final String SERIALIZED_NAME_TOTAL_ITEMS = "totalItems";
  @SerializedName(SERIALIZED_NAME_TOTAL_ITEMS)
  private Integer totalItems;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Integer offset;


  public AudienceSearchMetadataV1 totalItems(Integer totalItems) {
    
    this.totalItems = totalItems;
    return this;
  }

   /**
   * Total number of items
   * @return totalItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total number of items")

  public Integer getTotalItems() {
    return totalItems;
  }


  public void setTotalItems(Integer totalItems) {
    this.totalItems = totalItems;
  }


  public AudienceSearchMetadataV1 limit(Integer limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Max item of the current page
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Max item of the current page")

  public Integer getLimit() {
    return limit;
  }


  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public AudienceSearchMetadataV1 offset(Integer offset) {
    
    this.offset = offset;
    return this;
  }

   /**
   * Number of item to skip
   * @return offset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of item to skip")

  public Integer getOffset() {
    return offset;
  }


  public void setOffset(Integer offset) {
    this.offset = offset;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AudienceSearchMetadataV1 audienceSearchMetadataV1 = (AudienceSearchMetadataV1) o;
    return Objects.equals(this.totalItems, audienceSearchMetadataV1.totalItems) &&
        Objects.equals(this.limit, audienceSearchMetadataV1.limit) &&
        Objects.equals(this.offset, audienceSearchMetadataV1.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalItems, limit, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AudienceSearchMetadataV1 {\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

