/*
 * Criteo API
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.marketingsolutions.preview.JSON;

/**
 * An ad-level impression tracking rule. The rule calls its url when an impression it covers is served. It  applies either to the whole ad (no display size set) or to one display size (displayWidth and displayHeight  both set).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExamAdImpressionTracking {
  public static final String SERIALIZED_NAME_BINDING_ID = "bindingId";
  @SerializedName(SERIALIZED_NAME_BINDING_ID)
  private String bindingId;

  public static final String SERIALIZED_NAME_DISPLAY_HEIGHT = "displayHeight";
  @SerializedName(SERIALIZED_NAME_DISPLAY_HEIGHT)
  private Integer displayHeight;

  public static final String SERIALIZED_NAME_DISPLAY_WIDTH = "displayWidth";
  @SerializedName(SERIALIZED_NAME_DISPLAY_WIDTH)
  private Integer displayWidth;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_VENDOR_ID = "vendorId";
  @SerializedName(SERIALIZED_NAME_VENDOR_ID)
  private String vendorId;

  public ExamAdImpressionTracking() {
  }

  public ExamAdImpressionTracking bindingId(String bindingId) {
    
    this.bindingId = bindingId;
    return this;
  }

   /**
   * Unique ID of the ad the rule belongs to. It always names the ad of the request path, so it can be left  out of a write; when it is sent it must match that ad, and a rule naming another one is refused.
   * @return bindingId
  **/
  @javax.annotation.Nullable

  public String getBindingId() {
    return bindingId;
  }


  public void setBindingId(String bindingId) {
    this.bindingId = bindingId;
  }


  public ExamAdImpressionTracking displayHeight(Integer displayHeight) {
    
    this.displayHeight = displayHeight;
    return this;
  }

   /**
   * The height in pixels of the display size this rule applies to. Set it together with displayWidth, and  leave both out for a rule that is not specific to a display size.
   * @return displayHeight
  **/
  @javax.annotation.Nullable

  public Integer getDisplayHeight() {
    return displayHeight;
  }


  public void setDisplayHeight(Integer displayHeight) {
    this.displayHeight = displayHeight;
  }


  public ExamAdImpressionTracking displayWidth(Integer displayWidth) {
    
    this.displayWidth = displayWidth;
    return this;
  }

   /**
   * The width in pixels of the display size this rule applies to. Set it together with displayHeight, and  leave both out for a rule that is not specific to a display size.
   * @return displayWidth
  **/
  @javax.annotation.Nullable

  public Integer getDisplayWidth() {
    return displayWidth;
  }


  public void setDisplayWidth(Integer displayWidth) {
    this.displayWidth = displayWidth;
  }


  public ExamAdImpressionTracking id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique ID of the impression tracking rule. Leave it out to create a rule; send back the ID of an  existing rule to update it. Rules of the ad that are absent from a write request are deleted.
   * @return id
  **/
  @javax.annotation.Nullable

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ExamAdImpressionTracking url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The url called when an impression covered by this rule is served.
   * @return url
  **/
  @javax.annotation.Nullable

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public ExamAdImpressionTracking vendorId(String vendorId) {
    
    this.vendorId = vendorId;
    return this;
  }

   /**
   * Unique ID of the third party vendor the tracking url belongs to.
   * @return vendorId
  **/
  @javax.annotation.Nullable

  public String getVendorId() {
    return vendorId;
  }


  public void setVendorId(String vendorId) {
    this.vendorId = vendorId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExamAdImpressionTracking instance itself
   */
  public ExamAdImpressionTracking putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExamAdImpressionTracking examAdImpressionTracking = (ExamAdImpressionTracking) o;
    return Objects.equals(this.bindingId, examAdImpressionTracking.bindingId) &&
        Objects.equals(this.displayHeight, examAdImpressionTracking.displayHeight) &&
        Objects.equals(this.displayWidth, examAdImpressionTracking.displayWidth) &&
        Objects.equals(this.id, examAdImpressionTracking.id) &&
        Objects.equals(this.url, examAdImpressionTracking.url) &&
        Objects.equals(this.vendorId, examAdImpressionTracking.vendorId)&&
        Objects.equals(this.additionalProperties, examAdImpressionTracking.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(bindingId, displayHeight, displayWidth, id, url, vendorId, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExamAdImpressionTracking {\n");
    sb.append("    bindingId: ").append(toIndentedString(bindingId)).append("\n");
    sb.append("    displayHeight: ").append(toIndentedString(displayHeight)).append("\n");
    sb.append("    displayWidth: ").append(toIndentedString(displayWidth)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    vendorId: ").append(toIndentedString(vendorId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bindingId");
    openapiFields.add("displayHeight");
    openapiFields.add("displayWidth");
    openapiFields.add("id");
    openapiFields.add("url");
    openapiFields.add("vendorId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExamAdImpressionTracking
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExamAdImpressionTracking.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExamAdImpressionTracking is not found in the empty JSON string", ExamAdImpressionTracking.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("bindingId") != null && !jsonObj.get("bindingId").isJsonNull()) && !jsonObj.get("bindingId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bindingId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bindingId").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("vendorId") != null && !jsonObj.get("vendorId").isJsonNull()) && !jsonObj.get("vendorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vendorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendorId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExamAdImpressionTracking.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExamAdImpressionTracking' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExamAdImpressionTracking> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExamAdImpressionTracking.class));

       return (TypeAdapter<T>) new TypeAdapter<ExamAdImpressionTracking>() {
           @Override
           public void write(JsonWriter out, ExamAdImpressionTracking value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExamAdImpressionTracking read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExamAdImpressionTracking instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExamAdImpressionTracking given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExamAdImpressionTracking
  * @throws IOException if the JSON string is invalid with respect to ExamAdImpressionTracking
  */
  public static ExamAdImpressionTracking fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExamAdImpressionTracking.class);
  }

 /**
  * Convert an instance of ExamAdImpressionTracking to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

