/*
 * Criteo API
 * Criteo publicly exposed API
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.marketingsolutions.preview.model.ImageShape;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity consists of multiple images in different ratios and a headline text.
 */
@ApiModel(description = "Entity consists of multiple images in different ratios and a headline text.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ImageSet {
  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  private List<ImageShape> images = new ArrayList<>();

  public static final String SERIALIZED_NAME_HEADLINE_TEXT = "headlineText";
  @SerializedName(SERIALIZED_NAME_HEADLINE_TEXT)
  private String headlineText;


  public ImageSet images(List<ImageShape> images) {
    
    this.images = images;
    return this;
  }

  public ImageSet addImagesItem(ImageShape imagesItem) {
    this.images.add(imagesItem);
    return this;
  }

   /**
   * The images&#39; urls with their shapes.
   * @return images
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The images' urls with their shapes.")

  public List<ImageShape> getImages() {
    return images;
  }


  public void setImages(List<ImageShape> images) {
    this.images = images;
  }


  public ImageSet headlineText(String headlineText) {
    
    this.headlineText = headlineText;
    return this;
  }

   /**
   * The headline of the image set
   * @return headlineText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The headline of the image set")

  public String getHeadlineText() {
    return headlineText;
  }


  public void setHeadlineText(String headlineText) {
    this.headlineText = headlineText;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSet imageSet = (ImageSet) o;
    return Objects.equals(this.images, imageSet.images) &&
        Objects.equals(this.headlineText, imageSet.headlineText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(images, headlineText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSet {\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    headlineText: ").append(toIndentedString(headlineText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

