/*
 * Criteo API
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.marketingsolutions.preview.JSON;

/**
 * Colors of the different elements of a Showcase creative.  All values are valid RGB24 hexadecimal colors (e.g. \&quot;#AB00FF\&quot;).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ShowcaseColors {
  public static final String SERIALIZED_NAME_BODY_TEXT_COLOR = "bodyTextColor";
  @SerializedName(SERIALIZED_NAME_BODY_TEXT_COLOR)
  private String bodyTextColor;

  public static final String SERIALIZED_NAME_CREATIVE_BACKGROUND_COLOR = "creativeBackgroundColor";
  @SerializedName(SERIALIZED_NAME_CREATIVE_BACKGROUND_COLOR)
  private String creativeBackgroundColor;

  public static final String SERIALIZED_NAME_PRICES_COLOR = "pricesColor";
  @SerializedName(SERIALIZED_NAME_PRICES_COLOR)
  private String pricesColor;

  public ShowcaseColors() {
  }

  public ShowcaseColors bodyTextColor(String bodyTextColor) {
    
    this.bodyTextColor = bodyTextColor;
    return this;
  }

   /**
   * Color of the creative&#39;s body text.  A valid RGB24 color in hexadecimal (e.g. \&quot;#AB00FF\&quot;).
   * @return bodyTextColor
  **/
  @javax.annotation.Nonnull

  public String getBodyTextColor() {
    return bodyTextColor;
  }


  public void setBodyTextColor(String bodyTextColor) {
    this.bodyTextColor = bodyTextColor;
  }


  public ShowcaseColors creativeBackgroundColor(String creativeBackgroundColor) {
    
    this.creativeBackgroundColor = creativeBackgroundColor;
    return this;
  }

   /**
   * Color of the creative&#39;s background.  A valid RGB24 color in hexadecimal (e.g. \&quot;#AB00FF\&quot;).
   * @return creativeBackgroundColor
  **/
  @javax.annotation.Nonnull

  public String getCreativeBackgroundColor() {
    return creativeBackgroundColor;
  }


  public void setCreativeBackgroundColor(String creativeBackgroundColor) {
    this.creativeBackgroundColor = creativeBackgroundColor;
  }


  public ShowcaseColors pricesColor(String pricesColor) {
    
    this.pricesColor = pricesColor;
    return this;
  }

   /**
   * Color of the creative&#39;s prices.  A valid RGB24 color in hexadecimal (e.g. \&quot;#AB00FF\&quot;).
   * @return pricesColor
  **/
  @javax.annotation.Nonnull

  public String getPricesColor() {
    return pricesColor;
  }


  public void setPricesColor(String pricesColor) {
    this.pricesColor = pricesColor;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ShowcaseColors instance itself
   */
  public ShowcaseColors putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowcaseColors showcaseColors = (ShowcaseColors) o;
    return Objects.equals(this.bodyTextColor, showcaseColors.bodyTextColor) &&
        Objects.equals(this.creativeBackgroundColor, showcaseColors.creativeBackgroundColor) &&
        Objects.equals(this.pricesColor, showcaseColors.pricesColor)&&
        Objects.equals(this.additionalProperties, showcaseColors.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bodyTextColor, creativeBackgroundColor, pricesColor, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowcaseColors {\n");
    sb.append("    bodyTextColor: ").append(toIndentedString(bodyTextColor)).append("\n");
    sb.append("    creativeBackgroundColor: ").append(toIndentedString(creativeBackgroundColor)).append("\n");
    sb.append("    pricesColor: ").append(toIndentedString(pricesColor)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bodyTextColor");
    openapiFields.add("creativeBackgroundColor");
    openapiFields.add("pricesColor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("bodyTextColor");
    openapiRequiredFields.add("creativeBackgroundColor");
    openapiRequiredFields.add("pricesColor");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ShowcaseColors
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ShowcaseColors.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ShowcaseColors is not found in the empty JSON string", ShowcaseColors.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ShowcaseColors.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("bodyTextColor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bodyTextColor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bodyTextColor").toString()));
      }
      if (!jsonObj.get("creativeBackgroundColor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creativeBackgroundColor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creativeBackgroundColor").toString()));
      }
      if (!jsonObj.get("pricesColor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pricesColor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pricesColor").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ShowcaseColors.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ShowcaseColors' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ShowcaseColors> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ShowcaseColors.class));

       return (TypeAdapter<T>) new TypeAdapter<ShowcaseColors>() {
           @Override
           public void write(JsonWriter out, ShowcaseColors value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ShowcaseColors read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ShowcaseColors instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ShowcaseColors given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ShowcaseColors
  * @throws IOException if the JSON string is invalid with respect to ShowcaseColors
  */
  public static ShowcaseColors fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ShowcaseColors.class);
  }

 /**
  * Convert an instance of ShowcaseColors to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

