/*
 * Criteo API
 * Criteo API - MarketingSolutions
 *
 * The version of the OpenAPI document: Experimental
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.marketingsolutions.experimental.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.marketingsolutions.experimental.JSON;

/**
 * Number of offers added, updated, deleted and left unchanged by the ingestion, compared to the previous one.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CatalogIngestionReportingDelta {
  public static final String SERIALIZED_NAME_ADDED_OFFERS = "addedOffers";
  @SerializedName(SERIALIZED_NAME_ADDED_OFFERS)
  private Long addedOffers;

  public static final String SERIALIZED_NAME_DELETED_OFFERS = "deletedOffers";
  @SerializedName(SERIALIZED_NAME_DELETED_OFFERS)
  private Long deletedOffers;

  public static final String SERIALIZED_NAME_UNCHANGED_OFFERS = "unchangedOffers";
  @SerializedName(SERIALIZED_NAME_UNCHANGED_OFFERS)
  private Long unchangedOffers;

  public static final String SERIALIZED_NAME_UPDATED_OFFERS = "updatedOffers";
  @SerializedName(SERIALIZED_NAME_UPDATED_OFFERS)
  private Long updatedOffers;

  public CatalogIngestionReportingDelta() {
  }

  public CatalogIngestionReportingDelta addedOffers(Long addedOffers) {
    
    this.addedOffers = addedOffers;
    return this;
  }

   /**
   * Get addedOffers
   * @return addedOffers
  **/
  @javax.annotation.Nullable

  public Long getAddedOffers() {
    return addedOffers;
  }


  public void setAddedOffers(Long addedOffers) {
    this.addedOffers = addedOffers;
  }


  public CatalogIngestionReportingDelta deletedOffers(Long deletedOffers) {
    
    this.deletedOffers = deletedOffers;
    return this;
  }

   /**
   * Get deletedOffers
   * @return deletedOffers
  **/
  @javax.annotation.Nullable

  public Long getDeletedOffers() {
    return deletedOffers;
  }


  public void setDeletedOffers(Long deletedOffers) {
    this.deletedOffers = deletedOffers;
  }


  public CatalogIngestionReportingDelta unchangedOffers(Long unchangedOffers) {
    
    this.unchangedOffers = unchangedOffers;
    return this;
  }

   /**
   * Get unchangedOffers
   * @return unchangedOffers
  **/
  @javax.annotation.Nullable

  public Long getUnchangedOffers() {
    return unchangedOffers;
  }


  public void setUnchangedOffers(Long unchangedOffers) {
    this.unchangedOffers = unchangedOffers;
  }


  public CatalogIngestionReportingDelta updatedOffers(Long updatedOffers) {
    
    this.updatedOffers = updatedOffers;
    return this;
  }

   /**
   * Get updatedOffers
   * @return updatedOffers
  **/
  @javax.annotation.Nullable

  public Long getUpdatedOffers() {
    return updatedOffers;
  }


  public void setUpdatedOffers(Long updatedOffers) {
    this.updatedOffers = updatedOffers;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CatalogIngestionReportingDelta instance itself
   */
  public CatalogIngestionReportingDelta putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogIngestionReportingDelta catalogIngestionReportingDelta = (CatalogIngestionReportingDelta) o;
    return Objects.equals(this.addedOffers, catalogIngestionReportingDelta.addedOffers) &&
        Objects.equals(this.deletedOffers, catalogIngestionReportingDelta.deletedOffers) &&
        Objects.equals(this.unchangedOffers, catalogIngestionReportingDelta.unchangedOffers) &&
        Objects.equals(this.updatedOffers, catalogIngestionReportingDelta.updatedOffers)&&
        Objects.equals(this.additionalProperties, catalogIngestionReportingDelta.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addedOffers, deletedOffers, unchangedOffers, updatedOffers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogIngestionReportingDelta {\n");
    sb.append("    addedOffers: ").append(toIndentedString(addedOffers)).append("\n");
    sb.append("    deletedOffers: ").append(toIndentedString(deletedOffers)).append("\n");
    sb.append("    unchangedOffers: ").append(toIndentedString(unchangedOffers)).append("\n");
    sb.append("    updatedOffers: ").append(toIndentedString(updatedOffers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("addedOffers");
    openapiFields.add("deletedOffers");
    openapiFields.add("unchangedOffers");
    openapiFields.add("updatedOffers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CatalogIngestionReportingDelta
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CatalogIngestionReportingDelta.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CatalogIngestionReportingDelta is not found in the empty JSON string", CatalogIngestionReportingDelta.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CatalogIngestionReportingDelta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CatalogIngestionReportingDelta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CatalogIngestionReportingDelta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CatalogIngestionReportingDelta.class));

       return (TypeAdapter<T>) new TypeAdapter<CatalogIngestionReportingDelta>() {
           @Override
           public void write(JsonWriter out, CatalogIngestionReportingDelta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CatalogIngestionReportingDelta read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CatalogIngestionReportingDelta instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CatalogIngestionReportingDelta given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CatalogIngestionReportingDelta
  * @throws IOException if the JSON string is invalid with respect to CatalogIngestionReportingDelta
  */
  public static CatalogIngestionReportingDelta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CatalogIngestionReportingDelta.class);
  }

 /**
  * Convert an instance of CatalogIngestionReportingDelta to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

