/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.retailmedia.preview.model.CampaignAttributionRequest;
import com.criteo.api.retailmedia.preview.model.NillableOfCampaignCappingTargetRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.retailmedia.preview.JSON;

/**
 * Represents a model for updating specific properties of an existing display campaign.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DisplayCampaignPatchModel {
  public static final String SERIALIZED_NAME_ATTRIBUTION = "attribution";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTION)
  private CampaignAttributionRequest attribution;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_FREQUENCY_CAPPING = "frequencyCapping";
  @SerializedName(SERIALIZED_NAME_FREQUENCY_CAPPING)
  private NillableOfCampaignCappingTargetRequest frequencyCapping;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ON_BEHALF_COMPANY_NAME = "onBehalfCompanyName";
  @SerializedName(SERIALIZED_NAME_ON_BEHALF_COMPANY_NAME)
  private String onBehalfCompanyName;

  public DisplayCampaignPatchModel() {
  }

  public DisplayCampaignPatchModel attribution(CampaignAttributionRequest attribution) {
    
    this.attribution = attribution;
    return this;
  }

   /**
   * Get attribution
   * @return attribution
  **/
  @javax.annotation.Nullable

  public CampaignAttributionRequest getAttribution() {
    return attribution;
  }


  public void setAttribution(CampaignAttributionRequest attribution) {
    this.attribution = attribution;
  }


  public DisplayCampaignPatchModel companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * The name of the company paying for the ad
   * @return companyName
  **/
  @javax.annotation.Nullable

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public DisplayCampaignPatchModel frequencyCapping(NillableOfCampaignCappingTargetRequest frequencyCapping) {
    
    this.frequencyCapping = frequencyCapping;
    return this;
  }

   /**
   * Get frequencyCapping
   * @return frequencyCapping
  **/
  @javax.annotation.Nullable

  public NillableOfCampaignCappingTargetRequest getFrequencyCapping() {
    return frequencyCapping;
  }


  public void setFrequencyCapping(NillableOfCampaignCappingTargetRequest frequencyCapping) {
    this.frequencyCapping = frequencyCapping;
  }


  public DisplayCampaignPatchModel name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the campaign.
   * @return name
  **/
  @javax.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DisplayCampaignPatchModel onBehalfCompanyName(String onBehalfCompanyName) {
    
    this.onBehalfCompanyName = onBehalfCompanyName;
    return this;
  }

   /**
   * The name of the company the ad is on behalf of.
   * @return onBehalfCompanyName
  **/
  @javax.annotation.Nullable

  public String getOnBehalfCompanyName() {
    return onBehalfCompanyName;
  }


  public void setOnBehalfCompanyName(String onBehalfCompanyName) {
    this.onBehalfCompanyName = onBehalfCompanyName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisplayCampaignPatchModel displayCampaignPatchModel = (DisplayCampaignPatchModel) o;
    return Objects.equals(this.attribution, displayCampaignPatchModel.attribution) &&
        Objects.equals(this.companyName, displayCampaignPatchModel.companyName) &&
        Objects.equals(this.frequencyCapping, displayCampaignPatchModel.frequencyCapping) &&
        Objects.equals(this.name, displayCampaignPatchModel.name) &&
        Objects.equals(this.onBehalfCompanyName, displayCampaignPatchModel.onBehalfCompanyName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(attribution, companyName, frequencyCapping, name, onBehalfCompanyName);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisplayCampaignPatchModel {\n");
    sb.append("    attribution: ").append(toIndentedString(attribution)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    frequencyCapping: ").append(toIndentedString(frequencyCapping)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    onBehalfCompanyName: ").append(toIndentedString(onBehalfCompanyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attribution");
    openapiFields.add("companyName");
    openapiFields.add("frequencyCapping");
    openapiFields.add("name");
    openapiFields.add("onBehalfCompanyName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DisplayCampaignPatchModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DisplayCampaignPatchModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DisplayCampaignPatchModel is not found in the empty JSON string", DisplayCampaignPatchModel.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DisplayCampaignPatchModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DisplayCampaignPatchModel` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `attribution`
      if (jsonObj.get("attribution") != null && !jsonObj.get("attribution").isJsonNull()) {
        CampaignAttributionRequest.validateJsonObject(jsonObj.getAsJsonObject("attribution"));
      }
      if ((jsonObj.get("companyName") != null && !jsonObj.get("companyName").isJsonNull()) && !jsonObj.get("companyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyName").toString()));
      }
      // validate the optional field `frequencyCapping`
      if (jsonObj.get("frequencyCapping") != null && !jsonObj.get("frequencyCapping").isJsonNull()) {
        NillableOfCampaignCappingTargetRequest.validateJsonObject(jsonObj.getAsJsonObject("frequencyCapping"));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("onBehalfCompanyName") != null && !jsonObj.get("onBehalfCompanyName").isJsonNull()) && !jsonObj.get("onBehalfCompanyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `onBehalfCompanyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("onBehalfCompanyName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DisplayCampaignPatchModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DisplayCampaignPatchModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DisplayCampaignPatchModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DisplayCampaignPatchModel.class));

       return (TypeAdapter<T>) new TypeAdapter<DisplayCampaignPatchModel>() {
           @Override
           public void write(JsonWriter out, DisplayCampaignPatchModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DisplayCampaignPatchModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DisplayCampaignPatchModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DisplayCampaignPatchModel
  * @throws IOException if the JSON string is invalid with respect to DisplayCampaignPatchModel
  */
  public static DisplayCampaignPatchModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DisplayCampaignPatchModel.class);
  }

 /**
  * Convert an instance of DisplayCampaignPatchModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

