/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.retailmedia.preview.model.SkuOfferLoad;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.retailmedia.preview.JSON;

/**
 * The request passed by the caller of the Load endpoint
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LoadSkuOffersRequest {
  public static final String SERIALIZED_NAME_SKU_OFFER_LOADS = "skuOfferLoads";
  @SerializedName(SERIALIZED_NAME_SKU_OFFER_LOADS)
  private List<SkuOfferLoad> skuOfferLoads = new ArrayList<>();

  public LoadSkuOffersRequest() {
  }

  public LoadSkuOffersRequest skuOfferLoads(List<SkuOfferLoad> skuOfferLoads) {
    
    this.skuOfferLoads = skuOfferLoads;
    return this;
  }

  public LoadSkuOffersRequest addSkuOfferLoadsItem(SkuOfferLoad skuOfferLoadsItem) {
    this.skuOfferLoads.add(skuOfferLoadsItem);
    return this;
  }

   /**
   * Get skuOfferLoads
   * @return skuOfferLoads
  **/
  @javax.annotation.Nonnull

  public List<SkuOfferLoad> getSkuOfferLoads() {
    return skuOfferLoads;
  }


  public void setSkuOfferLoads(List<SkuOfferLoad> skuOfferLoads) {
    this.skuOfferLoads = skuOfferLoads;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoadSkuOffersRequest loadSkuOffersRequest = (LoadSkuOffersRequest) o;
    return Objects.equals(this.skuOfferLoads, loadSkuOffersRequest.skuOfferLoads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skuOfferLoads);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoadSkuOffersRequest {\n");
    sb.append("    skuOfferLoads: ").append(toIndentedString(skuOfferLoads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("skuOfferLoads");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("skuOfferLoads");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LoadSkuOffersRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LoadSkuOffersRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoadSkuOffersRequest is not found in the empty JSON string", LoadSkuOffersRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!LoadSkuOffersRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoadSkuOffersRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LoadSkuOffersRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("skuOfferLoads").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `skuOfferLoads` to be an array in the JSON string but got `%s`", jsonObj.get("skuOfferLoads").toString()));
      }

      JsonArray jsonArrayskuOfferLoads = jsonObj.getAsJsonArray("skuOfferLoads");
      // validate the required field `skuOfferLoads` (array)
      for (int i = 0; i < jsonArrayskuOfferLoads.size(); i++) {
        SkuOfferLoad.validateJsonObject(jsonArrayskuOfferLoads.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoadSkuOffersRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoadSkuOffersRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoadSkuOffersRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoadSkuOffersRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<LoadSkuOffersRequest>() {
           @Override
           public void write(JsonWriter out, LoadSkuOffersRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoadSkuOffersRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoadSkuOffersRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoadSkuOffersRequest
  * @throws IOException if the JSON string is invalid with respect to LoadSkuOffersRequest
  */
  public static LoadSkuOffersRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoadSkuOffersRequest.class);
  }

 /**
  * Convert an instance of LoadSkuOffersRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

