/*
 * Criteo API
 * Criteo publicly exposed API
 *
 * The version of the OpenAPI document: Preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.preview.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.retailmedia.preview.model.CommonProblem;
import com.criteo.api.retailmedia.preview.model.PageMetadata;
import com.criteo.api.retailmedia.preview.model.RetailMediaAudienceV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Array of Audiences Returned as Part of Get RetailMedia Audience Request
 */
@ApiModel(description = "Array of Audiences Returned as Part of Get RetailMedia Audience Request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RetailMediaAudienceV2ListResponse {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<RetailMediaAudienceV2> data = new ArrayList<>();

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<CommonProblem> errors = null;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private List<CommonProblem> warnings = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private PageMetadata metadata;


   /**
   * data
   * @return data
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "data")

  public List<RetailMediaAudienceV2> getData() {
    return data;
  }




   /**
   * errors
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "errors")

  public List<CommonProblem> getErrors() {
    return errors;
  }




   /**
   * warnings
   * @return warnings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "warnings")

  public List<CommonProblem> getWarnings() {
    return warnings;
  }




  public RetailMediaAudienceV2ListResponse metadata(PageMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PageMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(PageMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetailMediaAudienceV2ListResponse retailMediaAudienceV2ListResponse = (RetailMediaAudienceV2ListResponse) o;
    return Objects.equals(this.data, retailMediaAudienceV2ListResponse.data) &&
        Objects.equals(this.errors, retailMediaAudienceV2ListResponse.errors) &&
        Objects.equals(this.warnings, retailMediaAudienceV2ListResponse.warnings) &&
        Objects.equals(this.metadata, retailMediaAudienceV2ListResponse.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errors, warnings, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetailMediaAudienceV2ListResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

