/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Experimental
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.experimental.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.criteo.api.retailmedia.experimental.JSON;

/**
 * Which categories of search keyword the line item is eligible to bid on.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExternalConquestingSettings {
  public static final String SERIALIZED_NAME_CONQUESTING_AD_STRATEGY_ENABLED = "conquestingAdStrategyEnabled";
  @SerializedName(SERIALIZED_NAME_CONQUESTING_AD_STRATEGY_ENABLED)
  private Boolean conquestingAdStrategyEnabled;

  public static final String SERIALIZED_NAME_DEFENSIVE_AD_STRATEGY_ENABLED = "defensiveAdStrategyEnabled";
  @SerializedName(SERIALIZED_NAME_DEFENSIVE_AD_STRATEGY_ENABLED)
  private Boolean defensiveAdStrategyEnabled;

  public static final String SERIALIZED_NAME_IS_AD_STRATEGY_LOCKED = "isAdStrategyLocked";
  @SerializedName(SERIALIZED_NAME_IS_AD_STRATEGY_LOCKED)
  private Boolean isAdStrategyLocked;

  public static final String SERIALIZED_NAME_NEUTRAL_AD_STRATEGY_ENABLED = "neutralAdStrategyEnabled";
  @SerializedName(SERIALIZED_NAME_NEUTRAL_AD_STRATEGY_ENABLED)
  private Boolean neutralAdStrategyEnabled;

  public ExternalConquestingSettings() {
  }

  public ExternalConquestingSettings conquestingAdStrategyEnabled(Boolean conquestingAdStrategyEnabled) {
    
    this.conquestingAdStrategyEnabled = conquestingAdStrategyEnabled;
    return this;
  }

   /**
   * Whether the line item may bid on competitors&#39; branded keywords. Defaults to false.
   * @return conquestingAdStrategyEnabled
  **/
  @javax.annotation.Nonnull

  public Boolean getConquestingAdStrategyEnabled() {
    return conquestingAdStrategyEnabled;
  }


  public void setConquestingAdStrategyEnabled(Boolean conquestingAdStrategyEnabled) {
    this.conquestingAdStrategyEnabled = conquestingAdStrategyEnabled;
  }


  public ExternalConquestingSettings defensiveAdStrategyEnabled(Boolean defensiveAdStrategyEnabled) {
    
    this.defensiveAdStrategyEnabled = defensiveAdStrategyEnabled;
    return this;
  }

   /**
   * Whether the line item may bid on the advertiser&#39;s own branded keywords. Defaults to true.
   * @return defensiveAdStrategyEnabled
  **/
  @javax.annotation.Nonnull

  public Boolean getDefensiveAdStrategyEnabled() {
    return defensiveAdStrategyEnabled;
  }


  public void setDefensiveAdStrategyEnabled(Boolean defensiveAdStrategyEnabled) {
    this.defensiveAdStrategyEnabled = defensiveAdStrategyEnabled;
  }


  public ExternalConquestingSettings isAdStrategyLocked(Boolean isAdStrategyLocked) {
    
    this.isAdStrategyLocked = isAdStrategyLocked;
    return this;
  }

   /**
   * Whether the keyword strategy flags have been set and can no longer be changed.
   * @return isAdStrategyLocked
  **/
  @javax.annotation.Nonnull

  public Boolean getIsAdStrategyLocked() {
    return isAdStrategyLocked;
  }


  public void setIsAdStrategyLocked(Boolean isAdStrategyLocked) {
    this.isAdStrategyLocked = isAdStrategyLocked;
  }


  public ExternalConquestingSettings neutralAdStrategyEnabled(Boolean neutralAdStrategyEnabled) {
    
    this.neutralAdStrategyEnabled = neutralAdStrategyEnabled;
    return this;
  }

   /**
   * Whether the line item may bid on generic, unbranded category keywords. Defaults to true.
   * @return neutralAdStrategyEnabled
  **/
  @javax.annotation.Nonnull

  public Boolean getNeutralAdStrategyEnabled() {
    return neutralAdStrategyEnabled;
  }


  public void setNeutralAdStrategyEnabled(Boolean neutralAdStrategyEnabled) {
    this.neutralAdStrategyEnabled = neutralAdStrategyEnabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalConquestingSettings externalConquestingSettings = (ExternalConquestingSettings) o;
    return Objects.equals(this.conquestingAdStrategyEnabled, externalConquestingSettings.conquestingAdStrategyEnabled) &&
        Objects.equals(this.defensiveAdStrategyEnabled, externalConquestingSettings.defensiveAdStrategyEnabled) &&
        Objects.equals(this.isAdStrategyLocked, externalConquestingSettings.isAdStrategyLocked) &&
        Objects.equals(this.neutralAdStrategyEnabled, externalConquestingSettings.neutralAdStrategyEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conquestingAdStrategyEnabled, defensiveAdStrategyEnabled, isAdStrategyLocked, neutralAdStrategyEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalConquestingSettings {\n");
    sb.append("    conquestingAdStrategyEnabled: ").append(toIndentedString(conquestingAdStrategyEnabled)).append("\n");
    sb.append("    defensiveAdStrategyEnabled: ").append(toIndentedString(defensiveAdStrategyEnabled)).append("\n");
    sb.append("    isAdStrategyLocked: ").append(toIndentedString(isAdStrategyLocked)).append("\n");
    sb.append("    neutralAdStrategyEnabled: ").append(toIndentedString(neutralAdStrategyEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("conquestingAdStrategyEnabled");
    openapiFields.add("defensiveAdStrategyEnabled");
    openapiFields.add("isAdStrategyLocked");
    openapiFields.add("neutralAdStrategyEnabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("conquestingAdStrategyEnabled");
    openapiRequiredFields.add("defensiveAdStrategyEnabled");
    openapiRequiredFields.add("isAdStrategyLocked");
    openapiRequiredFields.add("neutralAdStrategyEnabled");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExternalConquestingSettings
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExternalConquestingSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExternalConquestingSettings is not found in the empty JSON string", ExternalConquestingSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ExternalConquestingSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExternalConquestingSettings` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExternalConquestingSettings.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExternalConquestingSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExternalConquestingSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExternalConquestingSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExternalConquestingSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<ExternalConquestingSettings>() {
           @Override
           public void write(JsonWriter out, ExternalConquestingSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExternalConquestingSettings read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExternalConquestingSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExternalConquestingSettings
  * @throws IOException if the JSON string is invalid with respect to ExternalConquestingSettings
  */
  public static ExternalConquestingSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExternalConquestingSettings.class);
  }

 /**
  * Convert an instance of ExternalConquestingSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

