/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Experimental
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.experimental.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of the ingestion.
 */
@JsonAdapter(IngestionStatus.Adapter.class)
public enum IngestionStatus {
  
  InProgress("inProgress"),
  
  Finished("finished"),
  
  Failed("failed"),
  
  Blocked("blocked");

  private String value;

  IngestionStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IngestionStatus fromValue(String value) {
    for (IngestionStatus b : IngestionStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<IngestionStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final IngestionStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IngestionStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IngestionStatus.fromValue(value);
    }
  }
}

