/*
 * Criteo API
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Experimental
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.experimental.api;

import com.criteo.api.retailmedia.experimental.ApiCallback;
import com.criteo.api.retailmedia.experimental.ApiClient;
import com.criteo.api.retailmedia.experimental.ApiException;
import com.criteo.api.retailmedia.experimental.ApiResponse;
import com.criteo.api.retailmedia.experimental.Configuration;
import com.criteo.api.retailmedia.experimental.Pair;
import com.criteo.api.retailmedia.experimental.ProgressRequestBody;
import com.criteo.api.retailmedia.experimental.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.criteo.api.retailmedia.experimental.model.EntityResourceCollectionOutcomeBalanceV1AndMetadata;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class BalanceApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BalanceApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BalanceApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getPageOfBalancesV1
     * @param accountId The account to get balances for. (required)
     * @param limit The number of elements to be returned. (optional, default to 25)
     * @param limitToId The balance ids which the result is limited to. (optional)
     * @param offset The (zero-based) starting offset in the collection. (optional, default to 0)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPageOfBalancesV1Call(String accountId, Integer limit, List<String> limitToId, Integer offset, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/experimental/retail-media/accounts/{accountId}/balances"
            .replace("{" + "accountId" + "}", localVarApiClient.escapeString(accountId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (limitToId != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "limit-to-id", limitToId));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth", "oauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPageOfBalancesV1ValidateBeforeCall(String accountId, Integer limit, List<String> limitToId, Integer offset, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'accountId' is set
        if (accountId == null) {
            throw new ApiException("Missing the required parameter 'accountId' when calling getPageOfBalancesV1(Async)");
        }

        return getPageOfBalancesV1Call(accountId, limit, limitToId, offset, _callback);

    }

    /**
     * /experimental/retail-media/accounts/{accountId}/balances
     * Gets page of balance objects for the given account id.
     * @param accountId The account to get balances for. (required)
     * @param limit The number of elements to be returned. (optional, default to 25)
     * @param limitToId The balance ids which the result is limited to. (optional)
     * @param offset The (zero-based) starting offset in the collection. (optional, default to 0)
     * @return EntityResourceCollectionOutcomeBalanceV1AndMetadata
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public EntityResourceCollectionOutcomeBalanceV1AndMetadata getPageOfBalancesV1(String accountId, Integer limit, List<String> limitToId, Integer offset) throws ApiException {
        ApiResponse<EntityResourceCollectionOutcomeBalanceV1AndMetadata> localVarResp = getPageOfBalancesV1WithHttpInfo(accountId, limit, limitToId, offset);
        return localVarResp.getData();
    }

    /**
     * /experimental/retail-media/accounts/{accountId}/balances
     * Gets page of balance objects for the given account id.
     * @param accountId The account to get balances for. (required)
     * @param limit The number of elements to be returned. (optional, default to 25)
     * @param limitToId The balance ids which the result is limited to. (optional)
     * @param offset The (zero-based) starting offset in the collection. (optional, default to 0)
     * @return ApiResponse&lt;EntityResourceCollectionOutcomeBalanceV1AndMetadata&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<EntityResourceCollectionOutcomeBalanceV1AndMetadata> getPageOfBalancesV1WithHttpInfo(String accountId, Integer limit, List<String> limitToId, Integer offset) throws ApiException {
        okhttp3.Call localVarCall = getPageOfBalancesV1ValidateBeforeCall(accountId, limit, limitToId, offset, null);
        Type localVarReturnType = new TypeToken<EntityResourceCollectionOutcomeBalanceV1AndMetadata>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /experimental/retail-media/accounts/{accountId}/balances (asynchronously)
     * Gets page of balance objects for the given account id.
     * @param accountId The account to get balances for. (required)
     * @param limit The number of elements to be returned. (optional, default to 25)
     * @param limitToId The balance ids which the result is limited to. (optional)
     * @param offset The (zero-based) starting offset in the collection. (optional, default to 0)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPageOfBalancesV1Async(String accountId, Integer limit, List<String> limitToId, Integer offset, final ApiCallback<EntityResourceCollectionOutcomeBalanceV1AndMetadata> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPageOfBalancesV1ValidateBeforeCall(accountId, limit, limitToId, offset, _callback);
        Type localVarReturnType = new TypeToken<EntityResourceCollectionOutcomeBalanceV1AndMetadata>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
