/*
 * Criteo API
 * Criteo publicly exposed API
 *
 * The version of the OpenAPI document: 2023-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.api.retailmedia.v2023_01.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.api.retailmedia.v2023_01.model.CommonProblem;
import com.criteo.api.retailmedia.v2023_01.model.CreateRetailMediaAudienceV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Response of CreateAudienceRequestV2
 */
@ApiModel(description = "Response of CreateAudienceRequestV2")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RetailMediaAudienceV2Response {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private CreateRetailMediaAudienceV2 data;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<CommonProblem> errors = null;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private List<CommonProblem> warnings = null;


  public RetailMediaAudienceV2Response data(CreateRetailMediaAudienceV2 data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreateRetailMediaAudienceV2 getData() {
    return data;
  }


  public void setData(CreateRetailMediaAudienceV2 data) {
    this.data = data;
  }


   /**
   * errors
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "errors")

  public List<CommonProblem> getErrors() {
    return errors;
  }




   /**
   * warnings
   * @return warnings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "warnings")

  public List<CommonProblem> getWarnings() {
    return warnings;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetailMediaAudienceV2Response retailMediaAudienceV2Response = (RetailMediaAudienceV2Response) o;
    return Objects.equals(this.data, retailMediaAudienceV2Response.data) &&
        Objects.equals(this.errors, retailMediaAudienceV2Response.errors) &&
        Objects.equals(this.warnings, retailMediaAudienceV2Response.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errors, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetailMediaAudienceV2Response {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

